### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by kelbyfaessler** [ianrufus/youtube#2]
This is a duplicate of https://github.com/ianrufus/youtube/issues/1 but you should really fix it. I used your code as a starting point and it broke my docs. Others likely will run into the same issue.

See this line of code: https://github.com/ianrufus/youtube/blob/main/fastapi-stripe-webhook/app.py#L68

Change `Header(str)` to `Header(None)`

**Comment by ghost** [comment]
@KelbyFaessler, great catch! I haven't seen @ianrufus active in recent months, maybe you could put up a PR to fix it? :)
